// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mobile.Models;

namespace mobile.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211109093054_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("mobile.Models.Catalog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("marca")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("nota1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("nota2")
                        .HasColumnType("TEXT");

                    b.Property<string>("nume")
                        .HasColumnType("TEXT");

                    b.Property<string>("prenume")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Catalogs");
                });
#pragma warning restore 612, 618
        }
    }
}
